name=M5Unit-WEIGHT
version=0.1.0
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack UNIT WEIGHT using M5UnitUnified
paragraph=Supports UnitWeightI2C (SKU:U180) and MiniScales (SKU:U177) for weight measurement with configurable filters and calibration.
category=Device Control
url=https://github.com/m5stack/M5Unit-WEIGHT
architectures=esp32
includes=M5UnitUnifiedWEIGHT.h
depends=M5UnitUnified,M5Utility,M5HAL
