name: Build(arduino-m5stack)

env:
  SKETCH_NAMES_FIND_START: ./examples/UnitUnified
  REQUIRED_LIBRARIES: M5Unified,M5UnitUnified

on:
  push:
    tags-ignore:
      - '*.*.*'
      - 'v*.*.*'
    branches:
      - '*'
    paths:
      - 'src/unit/**.cpp'
      - 'src/unit/**.hpp'
      - 'src/unit/**.h'
      - 'src/unit/**.c'
      - 'test/**.cpp'
      - 'test/**.hpp'
      - 'test/**.h'
      - 'test/**.c'
      - 'examples/UnitUnified/**.ino'
      - 'examples/UnitUnified/**.cpp'
      - 'examples/UnitUnified/**.hpp'
      - 'examples/UnitUnified/**.h'
      - 'examples/UnitUnified/**.c'
      - '**arduino-m5-build-check.yml'
  pull_request:
    paths:
      - 'src/unit/**.cpp'
      - 'src/unit/**.hpp'
      - 'src/unit/**.h'
      - 'src/unit/**.c'
      - 'test/**.cpp'
      - 'test/**.hpp'
      - 'test/**.h'
      - 'test/**.c'
      - 'examples/UnitUnified/**.ino'
      - 'examples/UnitUnified/**.cpp'
      - 'examples/UnitUnified/**.hpp'
      - 'examples/UnitUnified/**.h'
      - 'examples/UnitUnified/**.c'
      - '**arduino-m5-build-check.yml'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.unit }}:${{ matrix.sketch }}:${{matrix.board}}@${{matrix.platform-version}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
#      max-parallel: 1
      matrix:
        platform-url:
          - https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json

        sketch:
          - PlotToSerial

        unit:
          - UnitWeightI2C
          - UnitMiniScales

        board:
          - m5stack_atom
          - m5stack_atoms3
          - m5stack_atoms3r
          - m5stack_capsule
#          - m5stack_cardputer
          - m5stack_core
          - m5stack_core2
          - m5stack_coreink
          - m5stack_cores3
          - m5stack_dial
          - m5stack_dinmeter
          - m5stack_fire
          - m5stack_paper
#          - m5stack_poe_cam
#          - m5stack_stamp_c3
#          - m5stack_stamp_pico
          - m5stack_stamp_s3
#          - m5stack_station
#          - m5stack_stickc
          - m5stack_stickc_plus
          - m5stack_stickc_plus2
#          - m5stack_timer_cam
#          - m5stack_tough
#          - m5stack_unit_cam
#          - m5stack_unit_cams3

        platform-version:
          - 2.1.2

        platform:
          - m5stack

        archi:
          - esp32

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Build 
      - name: Compile examples
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: ${{ matrix.platform }}:${{ matrix.archi }}:${{ matrix.board }}
          arduino-platform: ${{ matrix.platform }}:${{ matrix.archi }}@${{ matrix.platform-version }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          extra-arduino-cli-args: ${{ matrix.cli-args }}
          #build-properties: ${{ toJson(matrix.build-properties) }}
          sketch-names: ${{ matrix.sketch }}.ino
          sketch-names-find-start: ${{ env.SKETCH_NAMES_FIND_START }}/${{ matrix.unit }}
          #sketches-exclude: ${{ matrix.sketches-exclude }}

